### PR TITLE
Features/csv headers

### PR DESCRIPTION
**Pull request by johntrandall**
Adds headers to CSV output

### CODE REVIEW

**Comment by johntrandall** [comment]
fixes https://github.com/kyamaguchi/amazon_order/issues/3

**Comment by kyamaguchi** [comment]
I added writer_spec.rb .
You can write test for csv header in writer_spec.rb instead of client_spec.rb .

Example:

```
  describe '#generate_csv' do
    it "prints data of products" do
      writer = AmazonOrder::Writer.new('spec/fixtures/files/*')
      order_file, product_file = writer.generate_csv
      expect(File.read(order_file)).to ...
      expect(File.read(product_file)).to ...
```

**Comment by johntrandall** [comment]
Set all client specs to pending so that they don't run on CI, because they have external dependancies.

**Comment by kyamaguchi** [comment]
Have you fixed and pushed the changes?
force push on the branch is fine.

**Comment by johntrandall** [comment]
I did. I mis-spoke. I didn't remove client_spec. I just set all client specs to pending so they don't run on CI.

**Comment by kyamaguchi** [comment]
I have my own client_spec which is in progress.
I expect client_spec to be removed in this pull request.
And want an example for header in writer_spec. (Or I could do this later if you just removed the client_spec.)

**Comment by johntrandall** [comment]
deleted client_spec for now. Will add to writer_spec when I have more time.

**Pull request merged**
